libmolgrid: Grid< Dtype, NumDims, isCUDA > Class Template Reference
Grid< Dtype, NumDims, isCUDA > Class Template Reference
#include <grid.h>
Public Types
using type = Dtype
using subgrid_t = Grid< Dtype, NumDims-1, isCUDA >
using managed_t = ManagedGrid< Dtype, NumDims >
using cpu_grid_t = Grid< Dtype, NumDims, false >
using gpu_grid_t = Grid< Dtype, NumDims, true >
Public Member Functions
CUDA_CALLABLE_MEMBER const size_t * dimensions () const
CUDA_CALLABLE_MEMBER size_t dimension (size_t i) const
CUDA_CALLABLE_MEMBER const size_t * offsets () const
CUDA_CALLABLE_MEMBER size_t offset (size_t i) const
CUDA_CALLABLE_MEMBER size_t size () const
CUDA_CALLABLE_MEMBER Dtype * data () const
CUDA_CALLABLE_MEMBER void set_buffer (Dtype *ptr)
Grid ()
template<typename... I>
Grid (Dtype *const d, I... sizes)
Grid (Dtype *const d, size_t *sizes)
Grid (const Grid &)=default
~Grid ()=default
CUDA_CALLABLE_MEMBER subgrid_t operator[] (size_t i) const
template<typename... I>
CUDA_CALLABLE_MEMBER Dtype & operator() (I... indices)
template<typename... I>
CUDA_CALLABLE_MEMBER Dtype operator() (I... indices) const
template<typename... I>
CUDA_CALLABLE_MEMBER Dtype * address (I... indices)
template<typename... I>
CUDA_CALLABLE_MEMBER const Dtype * address (I... indices) const
template<bool destCUDA>
size_t copyTo (Grid< Dtype, NumDims, destCUDA > &dest) const
template<bool srcCUDA>
size_t copyFrom (const Grid< Dtype, NumDims, srcCUDA > &src)
void fill_zero ()
CUDA_CALLABLE_MEMBER Grid (const Grid< Dtype, NumDims+1, isCUDA > &G, size_t i)
Static Public Attributes
static constexpr size_t N = NumDims
static constexpr bool GPU = isCUDA
Protected Member Functions
template<typename... I>
CUDA_CALLABLE_MEMBER size_t getPos (I... indices) const
CUDA_CALLABLE_MEMBER void check_index (size_t i, size_t dim) const
Protected Attributes
Dtype * buffer
size_t dims [NumDims]
size_t offs [NumDims]
Detailed Description
template<typename Dtype, std::size_t NumDims, bool isCUDA = false>
class libmolgrid::Grid< Dtype, NumDims, isCUDA >
A dense array of memory stored on the CPU. The memory is owned and managed external to this class. The location and size of the memory should not change during the lifetime of the grid. If isCUDA is true, data should only be accessed in kernels.
Member Typedef Documentation
type
using type = Dtype
subgrid_t
using subgrid_t = Grid<Dtype,NumDims-1,isCUDA>
managed_t
using managed_t = ManagedGrid<Dtype,NumDims>
cpu_grid_t
using cpu_grid_t = Grid<Dtype,NumDims,false>
gpu_grid_t
using gpu_grid_t = Grid<Dtype,NumDims,true>
Constructor & Destructor Documentation
Grid() [1/5]
Grid () inline
Empty grid constructor.
Referenced by Grid< Dtype, NumDims, true >::Grid().
Grid() [2/5]
Grid (Dtype *const d, I... sizes) inline
Grid constructor.
Provide pointer and dimensions specified as arguments
Grid() [3/5]
Grid (Dtype *const d, size_t * sizes) inline
Grid constructor.
Provide pointer and dimensions array specified as arguments. sizes must contain NumDims values.
Grid() [4/5]
Grid (const Grid< Dtype, NumDims, isCUDA > &) default
~Grid()
~Grid () default
Referenced by Grid< Dtype, NumDims, true >::Grid().
Grid() [5/5]
CUDA_CALLABLE_MEMBER Grid (const Grid< Dtype, NumDims+1, isCUDA > & G, size_t i) inline explicit
Member Function Documentation
getPos()
CUDA_CALLABLE_MEMBER size_t getPos (I... indices) const inline protected
Referenced by Grid< Dtype, NumDims, true >::address(), and Grid< Dtype, NumDims, true >::operator()().
check_index()
CUDA_CALLABLE_MEMBER void check_index (size_t i, size_t dim) const inline protected
Referenced by Grid< Dtype, NumDims, true >::dimension(), Grid< Dtype, 1, isCUDA >::dimension(), Grid< Dtype, NumDims, true >::operator[](), and Grid< Dtype, 1, isCUDA >::operator[]().
dimensions()
CUDA_CALLABLE_MEMBER const size_t* dimensions () const inline
dimensions along each axis
Referenced by ManagedGridBase< Dtype, 1 >::dimensions().
dimension()
CUDA_CALLABLE_MEMBER size_t dimension (size_t i) const inline
dimensions along specified axis
Referenced by Transform::backward(), GridMaker::backward(), GridMaker::backward_relevance(), GridMaker::check_index_args(), GridMaker::check_vector_args(), CoordinateSet::copyTo(), ManagedGridBase< Dtype, 1 >::dimension(), Example::extract_label(), Example::extract_labels(), Transform::forward(), GridMaker::forward(), Grid< Dtype, NumDims, true >::Grid(), Grid< Dtype, 1, isCUDA >::Grid(), Transform::is_identity(), ManagedGrid< Dtype, NumDims >::operator[](), libmolgrid::read_dx(), libmolgrid::read_dx_grids(), Example::sum_types(), CoordinateSet::sum_types(), libmolgrid::write_dx(), libmolgrid::write_dx_grids(), and libmolgrid::write_map().
offsets()
CUDA_CALLABLE_MEMBER const size_t* offsets () const inline
offset for each dimension, all indexing calculations use this
Referenced by ManagedGridBase< Dtype, 1 >::offsets().
offset()
CUDA_CALLABLE_MEMBER size_t offset (size_t i) const inline
offset for each dimension, all indexing calculations use this
Referenced by Grid< Dtype, NumDims, true >::Grid(), and ManagedGridBase< Dtype, 1 >::offset().
size()
CUDA_CALLABLE_MEMBER size_t size () const inline
number of elements in grid
Referenced by GridMaker::backward(), GridMaker::backward_relevance(), GridMaker::check_index_args(), GridMaker::check_vector_args(), ManagedGridBase< Dtype, 1 >::copyFrom(), Grid< Dtype, NumDims, true >::copyFrom(), Grid< Dtype, 1, isCUDA >::copyFrom(), ManagedGridBase< Dtype, 1 >::copyTo(), Grid< Dtype, NumDims, true >::copyTo(), Grid< Dtype, 1, isCUDA >::copyTo(), Grid< Dtype, NumDims, true >::fill_zero(), Grid< Dtype, 1, isCUDA >::fill_zero(), GridMaker::forward(), ManagedGridBase< Dtype, 1 >::resized(), and ManagedGridBase< Dtype, 1 >::size().
data()
CUDA_CALLABLE_MEMBER Dtype* data () const inline
pointer to underlying data
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom(), Grid< Dtype, NumDims, true >::copyFrom(), Grid< Dtype, 1, isCUDA >::copyFrom(), ManagedGridBase< Dtype, 1 >::copyInto(), ManagedGridBase< Dtype, 1 >::copyTo(), Grid< Dtype, NumDims, true >::copyTo(), Grid< Dtype, 1, isCUDA >::copyTo(), Example::extract_label(), Grid< Dtype, NumDims, true >::fill_zero(), Grid< Dtype, 1, isCUDA >::fill_zero(), GridMaker::forward(), Transform::is_identity(), ManagedGridBase< Dtype, 1 >::ongpu(), Example::sum_types(), and ManagedGridBase< Dtype, 1 >::togpu().
set_buffer()
CUDA_CALLABLE_MEMBER void set_buffer (Dtype * ptr) inline
set the underlying memory buffer - use with caution!
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu(), ManagedGridBase< Dtype, 1 >::alloc_and_set_gpu(), and ManagedGridBase< Dtype, 1 >::togpu().
operator[]()
CUDA_CALLABLE_MEMBER subgrid_t operator[] (size_t i) const inline
Bracket indexing.
Accessing data this way will be safe (indices are checked) and convenient, but not maximally efficient (unless the compiler is really good). Use operator() for fastest (but unchecked) access or access data directly.
operator()() [1/2]
CUDA_CALLABLE_MEMBER Dtype& operator() (I... indices) inline
Initializer list indexing.
operator()() [2/2]
CUDA_CALLABLE_MEMBER Dtype operator() (I... indices) const inline
address() [1/2]
CUDA_CALLABLE_MEMBER Dtype* address (I... indices) inline
Return memory address of specified index.
address() [2/2]
CUDA_CALLABLE_MEMBER const Dtype* address (I... indices) const inline
copyTo()
size_t copyTo (Grid< Dtype, NumDims, destCUDA > & dest) const inline
copy contents to dest
Sizes should be the same, but will narrow as necessary. Will copy across device/host.
copyFrom()
size_t copyFrom (const Grid< Dtype, NumDims, srcCUDA > & src) inline
copy contents from src
Sizes should be the same, but will narrow as necessary. Will copy across device/host.
fill_zero()
void fill_zero () inline
Set contents to zero.
Referenced by GridMaker::backward(), GridMaker::backward_relevance(), ManagedGridBase< Dtype, 1 >::fill_zero(), and CoordinateSet::sum_types().
Member Data Documentation
buffer
Dtype* buffer protected
Referenced by Grid< Dtype, NumDims, true >::data(), and Grid< Dtype, 1, isCUDA >::data().
dims
size_t dims[NumDims] protected
raw pointer to data
Referenced by Grid< Dtype, NumDims, true >::dimensions(), and Grid< Dtype, 1, isCUDA >::dimensions().
offs
size_t offs[NumDims] protected
Referenced by Grid< Dtype, NumDims, true >::offsets().
N
constexpr size_t N = NumDims static
GPU
constexpr bool GPU = isCUDA static
The documentation for this class was generated from the following file:
grid.h