libmolgrid: AtomIndexTyper Class Reference
AtomIndexTyper Class Reference abstract
#include <atom_typer.h>
Public Member Functions
AtomIndexTyper ()
virtual ~AtomIndexTyper ()
virtual unsigned num_types () const =0
virtual float get_atom_type_vector (OpenBabel::OBAtom *a, std::vector< float > &typ) const final
virtual std::pair< int, float > get_atom_type_index (OpenBabel::OBAtom *a) const =0
virtual std::pair< int, float > get_int_type (int t) const =0
virtual std::vector< std::string > get_type_names () const =0
virtual std::vector< float > get_type_radii () const
virtual bool is_vector_typer () const
Static Public Member Functions
static void set_names (unsigned ntypes, std::vector< std::string > &type_names, const std::vector< std::string > &names)
Detailed Description
Base class for generating numerical types along with atomic radius.
Constructor & Destructor Documentation
AtomIndexTyper()
AtomIndexTyper () inline
~AtomIndexTyper()
virtual ~AtomIndexTyper () inline virtual
Member Function Documentation
num_types()
virtual unsigned num_types () const pure virtual
return number of types
Reimplemented from AtomTyper.
Implemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
get_atom_type_vector()
virtual float get_atom_type_vector (OpenBabel::OBAtom * a, std::vector< float > & typ) const inline final virtual
Reimplemented from AtomTyper.
get_atom_type_index()
virtual std::pair<int,float> get_atom_type_index (OpenBabel::OBAtom * a) const pure virtual
return type index of a along with the apprioriate index
Reimplemented from AtomTyper.
Implemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
get_int_type()
virtual std::pair<int,float> get_int_type (int t) const pure virtual
return type and radius given a precomputed type, the meaning of which is specific to the implementation
Reimplemented from AtomTyper.
Implemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
get_type_names()
virtual std::vector<std::string> get_type_names () const pure virtual
return vector of string representations of types this isn't expected to be particularly efficient
Reimplemented from AtomTyper.
Implemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
get_type_radii()
virtual std::vector<float> get_type_radii () const inline virtual
if applicable to the typer, return the standard atomic radius of each type
Reimplemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
Referenced by CoordCache::set_coords().
set_names()
void set_names (unsigned ntypes, std::vector< std::string > & type_names, const std::vector< std::string > & names) static
Referenced by CallbackIndexTyper::CallbackIndexTyper(), and CallbackVectorTyper::CallbackVectorTyper().
is_vector_typer()
virtual bool is_vector_typer () const inline virtual
Reimplemented from AtomTyper.
The documentation for this class was generated from the following files:
atom_typer.h
atom_typer.cpp