libmolgrid: ExampleProvider Class Reference
--- title: ExampleProvider Class Reference layout: docs homepage: false hide: true ---
ExampleProvider Class Reference
#include <example_provider.h>
Public Member Functions
ExampleProvider (const ExampleProviderSettings &settings=ExampleProviderSettings())
ExampleProvider (const ExampleProviderSettings &settings, std::shared_ptr< AtomTyper > t)
ExampleProvider (const ExampleProviderSettings &settings, std::shared_ptr< AtomTyper > t1, std::shared_ptr< AtomTyper > t2)
ExampleProvider (const ExampleProviderSettings &settings, const std::vector< std::shared_ptr< AtomTyper > > &typrs, const std::vector< std::string > &molcaches=std::vector< std::string >())
ExampleProvider (std::shared_ptr< ExampleRefProvider > p, const ExampleExtractor &e)
virtual ~ExampleProvider ()
virtual void populate (const std::string &fname, int num_labels=-1)
virtual void populate (const std::vector< std::string > &fnames, int num_labels=-1)
virtual size_t num_labels () const
virtual void next (Example &ex)
virtual Example next ()
virtual void skip (unsigned n)
const ExampleProviderSettings & settings () const
virtual void next_batch (std::vector< Example > &ex, unsigned batch_size)
virtual std::vector< Example > next_batch (unsigned batch_size)
ExampleExtractor & get_extractor ()
ExampleRefProvider & get_provider ()
size_t num_types () const
std::vector< std::string > get_type_names () const
size_t size () const
Static Public Member Functions
static std::shared_ptr< ExampleRefProvider > createProvider (const ExampleProviderSettings &settings)
Detailed Description
Given a file of examples, provide Example classes one at a time This contains an exampleref provider, which can be configured using a single settings object if so desired, and an example extractor.
Constructor & Destructor Documentation
ExampleProvider() [1/5]
ExampleProvider (const ExampleProviderSettings & settings = ExampleProviderSettings())
Create provider using default gnina typing.
ExampleProvider() [2/5]
ExampleProvider (const ExampleProviderSettings & settings, std::shared_ptr< AtomTyper > t)
Create provider/extractor according to settings with single typer.
ExampleProvider() [3/5]
ExampleProvider (const ExampleProviderSettings & settings, std::shared_ptr< AtomTyper > t1, std::shared_ptr< AtomTyper > t2)
Create provider/extractor according to settings with two typers.
ExampleProvider() [4/5]
ExampleProvider (const ExampleProviderSettings & settings, const std::vector< std::shared_ptr< AtomTyper > > & typrs, const std::vector< std::string > & molcaches = std::vector<std::string>())
Create provider/extractor according to settings.
ExampleProvider() [5/5]
ExampleProvider (std::shared_ptr< ExampleRefProvider > p, const ExampleExtractor & e)
use provided provider
~ExampleProvider()
virtual ~ExampleProvider () inline virtual
Member Function Documentation
createProvider()
std::shared_ptr< ExampleRefProvider > createProvider (const ExampleProviderSettings & settings) static
return provider as specifyed by settings
populate() [1/2]
void populate (const std::string & fname, int num_labels = -1) virtual
load example file file fname and setup provider
populate() [2/2]
void populate (const std::vector< std::string > & fnames, int num_labels = -1) virtual
load multiple example files
num_labels()
virtual size_t num_labels () const inline virtual
return number of labels for each example (computed from first example only)
Referenced by ExampleProvider::populate().
next() [1/2]
void next (Example & ex) virtual
provide next example
next() [2/2]
virtual Example next () inline virtual
Referenced by ExampleProvider::next().
skip()
void skip (unsigned n) virtual
skip over the first n examples
settings()
const ExampleProviderSettings& settings () const inline
return settings created with
Referenced by ExampleProvider::createProvider().
next_batch() [1/2]
void next_batch (std::vector< Example > & ex, unsigned batch_size) virtual
provide a batch of examples
Referenced by ExampleProvider::next_batch().
next_batch() [2/2]
virtual std::vector<Example> next_batch (unsigned batch_size) inline virtual
get_extractor()
ExampleExtractor& get_extractor () inline
get_provider()
ExampleRefProvider& get_provider () inline
num_types()
size_t num_types () const inline
number of types
get_type_names()
std::vector<std::string> get_type_names () const inline
names of types (requires explicit typing)
size()
size_t size () const inline
return number of examples
The documentation for this class was generated from the following files:
example_provider.h
example_provider.cpp