libmolgrid: SubsettedElementTyper Class Reference
--- title: SubsettedElementTyper Class Reference layout: docs homepage: false hide: true ---
SubsettedElementTyper Class Reference abstract
#include <atom_typer.h>
Public Member Functions
SubsettedElementTyper (const std::vector< int > &map, bool include_catchall=true, unsigned maxe=84)
SubsettedElementTyper (const ElementIndexTyper &etyper, const std::vector< int > &map, bool include_catchall=true)
SubsettedElementTyper (const std::vector< std::vector< int > > &map, bool include_catchall=true, unsigned maxe=84)
SubsettedElementTyper (const ElementIndexTyper &etyper, const std::vector< std::vector< int > > &map, bool include_catchall=true)
virtual unsigned num_types () const
virtual unsigned num_types () const =0
virtual std::pair< int, float > get_atom_type_index (OpenBabel::OBAtom *a) const
virtual std::pair< int, float > get_int_type (int t) const
virtual std::vector< std::string > get_type_names () const
virtual std::vector< std::string > get_type_names () const =0
virtual std::vector< float > get_type_radii () const
virtual std::vector< float > get_type_radii () const
virtual float get_atom_type_vector (OpenBabel::OBAtom *a, std::vector< float > &typ) const final
virtual bool is_vector_typer () const
Static Public Member Functions
static void set_names (unsigned ntypes, std::vector< std::string > &type_names, const std::vector< std::string > &names)
Protected Attributes
SubsetAtomMapper mapper
ElementIndexTyper typer
std::vector< float > type_radii
Detailed Description
subsetting element types, derived class for convenient initialization
Constructor & Destructor Documentation
SubsettedElementTyper() [1/4]
SubsettedElementTyper (const std::vector< int > & map, bool include_catchall = true, unsigned maxe = 84) inline
SubsettedElementTyper() [2/4]
SubsettedElementTyper (const ElementIndexTyper & etyper, const std::vector< int > & map, bool include_catchall = true) inline
SubsettedElementTyper() [3/4]
SubsettedElementTyper (const std::vector< std::vector< int > > & map, bool include_catchall = true, unsigned maxe = 84) inline
SubsettedElementTyper() [4/4]
SubsettedElementTyper (const ElementIndexTyper & etyper, const std::vector< std::vector< int > > & map, bool include_catchall = true) inline
Member Function Documentation
num_types() [1/2]
virtual unsigned num_types inline virtual inherited
return number of types
num_types() [2/2]
virtual unsigned num_types () const pure virtual inherited
return number of types
Reimplemented from AtomTyper.
Implemented in MappedAtomIndexTyper< Mapper, Typer >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
Referenced by AtomIndexTyper::get_type_radii().
get_atom_type_index()
virtual std::pair<int,float> get_atom_type_index (OpenBabel::OBAtom * a) const inline virtual inherited
return type index of a
Implements AtomIndexTyper.
get_int_type()
virtual std::pair<int,float> get_int_type (int t) const inline virtual inherited
return type and radius given a precomputed type, the meaning of which is specific to the implementation
Implements AtomIndexTyper.
get_type_names() [1/2]
virtual std::vector<std::string> get_type_names inline virtual inherited
return vector of string representations of types this isn't expected to be particularly efficient
get_type_names() [2/2]
virtual std::vector<std::string> get_type_names () const pure virtual inherited
return vector of string representations of types this isn't expected to be particularly efficient
Reimplemented from AtomTyper.
Implemented in MappedAtomIndexTyper< Mapper, Typer >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
get_type_radii() [1/2]
virtual std::vector<float> get_type_radii inline virtual inherited
radii are the average of the underlying mapped types
get_type_radii() [2/2]
virtual std::vector<float> get_type_radii () const inline virtual inherited
if applicable to the typer, return the standard atomic radius of each type
Reimplemented in MappedAtomIndexTyper< Mapper, Typer >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, and GninaIndexTyper.
Referenced by CoordCache::set_coords().
get_atom_type_vector()
virtual float get_atom_type_vector (OpenBabel::OBAtom * a, std::vector< float > & typ) const inline final virtual inherited
Reimplemented from AtomTyper.
set_names()
void set_names (unsigned ntypes, std::vector< std::string > & type_names, const std::vector< std::string > & names) static inherited
Referenced by CallbackIndexTyper::CallbackIndexTyper(), and CallbackVectorTyper::CallbackVectorTyper().
is_vector_typer()
virtual bool is_vector_typer () const inline virtual inherited
Reimplemented from AtomTyper.
Member Data Documentation
mapper
SubsetAtomMapper mapper protected inherited
typer
ElementIndexTyper typer protected inherited
type_radii
std::vector<float> type_radii protected inherited
The documentation for this class was generated from the following file:
atom_typer.h