libmolgrid: UniformExampleRefProvider Class Reference
--- title: UniformExampleRefProvider Class Reference layout: docs homepage: false hide: true ---
UniformExampleRefProvider Class Reference
#include <exampleref_providers.h>
Public Member Functions
UniformExampleRefProvider ()
UniformExampleRefProvider (const ExampleProviderSettings &settings)
void addref (const ExampleRef &ex)
virtual size_t num_labels () const
void setup ()
void nextref (ExampleRef &ex)
unsigned size () const
virtual bool has_group () const
virtual void check_batch_size (unsigned bsize) const
virtual int populate (std::istream &lines, int numlabels)
Detailed Description
single array of examples, possibly shuffled
Constructor & Destructor Documentation
UniformExampleRefProvider() [1/2]
UniformExampleRefProvider () inline
UniformExampleRefProvider() [2/2]
UniformExampleRefProvider (const ExampleProviderSettings & settings) inline
Member Function Documentation
addref()
void addref (const ExampleRef & ex) virtual
Implements ExampleRefProvider.
num_labels()
virtual size_t num_labels () const inline virtual
return number of labels in an example
if provider has predetermined batch size
Implements ExampleRefProvider.
Referenced by BalancedExampleRefProvider::num_labels().
setup()
void setup () virtual
Implements ExampleRefProvider.
nextref()
void nextref (ExampleRef & ex) virtual
Implements ExampleRefProvider.
Referenced by BalancedExampleRefProvider::next_active(), and BalancedExampleRefProvider::next_decoy().
size()
unsigned size () const inline virtual
Implements ExampleRefProvider.
Referenced by BalancedExampleRefProvider::num_actives(), BalancedExampleRefProvider::num_decoys(), and BalancedExampleRefProvider::size().
has_group()
virtual bool has_group () const inline virtual inherited
Reimplemented in GroupedExampleRefProvider< Provider >.
check_batch_size()
virtual void check_batch_size (unsigned bsize) const inline virtual inherited
has group field
Reimplemented in GroupedExampleRefProvider< Provider >.
populate()
int populate (std::istream & lines, int numlabels) virtual inherited
read in all the example refs from lines, but does not setup
The documentation for this class was generated from the following files:
exampleref_providers.h
exampleref_providers.cpp