libmolgrid: CallbackIndexTyper Class Reference
--- title: CallbackIndexTyper Class Reference layout: docs homepage: false hide: true ---
CallbackIndexTyper Class Reference
#include <atom_typer.h>
Public Types
using AtomIndexTyperFunc = std::function< std::pair< int, float >(OpenBabel::OBAtom *a)>
Public Member Functions
CallbackIndexTyper (AtomIndexTyperFunc f, unsigned ntypes, const std::vector< std::string > &names=std::vector< std::string >())
virtual unsigned num_types () const
virtual std::pair< int, float > get_atom_type_index (OpenBabel::OBAtom *a) const
virtual std::pair< int, float > get_int_type (int t) const
virtual std::vector< std::string > get_type_names () const
virtual std::vector< float > get_type_radii () const
virtual float get_atom_type_vector (OpenBabel::OBAtom *a, std::vector< float > &typ) const final
virtual bool is_vector_typer () const
Static Public Member Functions
static void set_names (unsigned ntypes, std::vector< std::string > &type_names, const std::vector< std::string > &names)
Detailed Description
Use user-provided callback to do typing Must provide the number of types and their names.
Member Typedef Documentation
AtomIndexTyperFunc
using AtomIndexTyperFunc = std::function<std::pair<int,float>(OpenBabel::OBAtom* a)>
Constructor & Destructor Documentation
CallbackIndexTyper()
CallbackIndexTyper (AtomIndexTyperFunc f, unsigned ntypes, const std::vector< std::string > & names = std::vector<std::string>())
iniitalize callbacktyper, if names are not provided, numerical names will be generated
Member Function Documentation
num_types()
virtual unsigned num_types () const inline virtual
return number of types
Implements AtomIndexTyper.
Referenced by CallbackIndexTyper::get_atom_type_index(), CallbackIndexTyper::get_int_type(), and CallbackIndexTyper::get_type_radii().
get_atom_type_index()
virtual std::pair<int,float> get_atom_type_index (OpenBabel::OBAtom * a) const inline virtual
return type index of a
Implements AtomIndexTyper.
get_int_type()
virtual std::pair<int,float> get_int_type (int t) const inline virtual
return type and radius given a precomputed type, the meaning of which is specific to the implementation
Implements AtomIndexTyper.
get_type_names()
virtual std::vector<std::string> get_type_names () const inline virtual
return vector of string representations of types this isn't expected to be particularly efficient
Implements AtomIndexTyper.
get_type_radii()
virtual std::vector<float> get_type_radii () const inline virtual
if applicable to the typer, return the standard atomic radius of each type
Reimplemented from AtomIndexTyper.
get_atom_type_vector()
virtual float get_atom_type_vector (OpenBabel::OBAtom * a, std::vector< float > & typ) const inline final virtual inherited
Reimplemented from AtomTyper.
set_names()
void set_names (unsigned ntypes, std::vector< std::string > & type_names, const std::vector< std::string > & names) static inherited
Referenced by CallbackIndexTyper::CallbackIndexTyper(), and CallbackVectorTyper::CallbackVectorTyper().
is_vector_typer()
virtual bool is_vector_typer () const inline virtual inherited
Reimplemented from AtomTyper.
The documentation for this class was generated from the following files:
atom_typer.h
atom_typer.cpp