libmolgrid: Quaternion Class Reference
--- title: Quaternion Class Reference layout: docs homepage: false hide: true ---
Quaternion Class Reference
#include <quaternion.h>
Public Types
typedef float fl
Public Member Functions
__host__ __device__ Quaternion ()
__host__ __device__ Quaternion (fl A, fl B, fl C, fl D)
__host__ __device__ fl R_component_1 () const
__host__ __device__ fl R_component_2 () const
__host__ __device__ fl R_component_3 () const
__host__ __device__ fl R_component_4 () const
__host__ __device__ Quaternion & operator*= (const fl &r)
__host__ __device__ Quaternion & operator/= (const fl &r)
__host__ __device__ Quaternion operator/ (const fl &r)
__host__ __device__ Quaternion operator* (const Quaternion &r) const
__host__ __device__ Quaternion & operator*= (const Quaternion &r)
__host__ __device__ bool operator== (const Quaternion &r) const
__host__ __device__ Quaternion operator/ (const Quaternion &r)
__host__ __device__ Quaternion operator/= (const Quaternion &r)
__host__ __device__ Quaternion conj () const
__host__ __device__ float real () const
__host__ __device__ float norm () const
__host__ __device__ float3 rotate (fl x, fl y, fl z) const
__host__ __device__ float3 transform (fl x, fl y, fl z, float3 center, float3 translate) const
__host__ __device__ Quaternion inverse () const
Protected Attributes
fl a
fl b
fl c
fl d
Detailed Description
A CUDA friendly quaternion class. Single precision only for maximum CUDA performance.
Member Typedef Documentation
fl
typedef float fl
Constructor & Destructor Documentation
Quaternion() [1/2]
__host__ __device__ Quaternion () inline
Referenced by Quaternion::conj(), Quaternion::inverse(), Quaternion::operator*(), and Quaternion::operator/().
Quaternion() [2/2]
__host__ __device__ Quaternion (fl A, fl B, fl C, fl D) inline
Construct quaternion with real then unreal components.
Member Function Documentation
R_component_1()
__host__ __device__ fl R_component_1 () const inline
Return the real or scalar part.
Referenced by Quaternion::operator*(), Quaternion::operator/(), and Quaternion::real().
R_component_2()
__host__ __device__ fl R_component_2 () const inline
Return unreal[0].
Referenced by Quaternion::operator*(), Quaternion::operator/(), and Quaternion::rotate().
R_component_3()
__host__ __device__ fl R_component_3 () const inline
Return unreal[1].
Referenced by Quaternion::operator*(), Quaternion::operator/(), and Quaternion::rotate().
R_component_4()
__host__ __device__ fl R_component_4 () const inline
Return unreal[2].
Referenced by Quaternion::operator*(), Quaternion::operator/(), and Quaternion::rotate().
operator*=() [1/2]
__host__ __device__ Quaternion& operator*= (const fl & r) inline
In-place multiplication by scalar (element-wise)
operator/=() [1/2]
__host__ __device__ Quaternion& operator/= (const fl & r) inline
In-place division by scalar (element-wise)
operator/() [1/2]
__host__ __device__ Quaternion operator/ (const fl & r) inline
Division by scalar (element-wise)
operator*()
__host__ __device__ Quaternion operator* (const Quaternion & r) const inline
Quaternion multiplication.
operator*=() [2/2]
__host__ __device__ Quaternion& operator*= (const Quaternion & r) inline
Quaternion in-place multiplication.
operator==()
__host__ __device__ bool operator== (const Quaternion & r) const inline
check bit level equality
operator/() [2/2]
__host__ __device__ Quaternion operator/ (const Quaternion & r) inline
Quaternion divison.
operator/=() [2/2]
__host__ __device__ Quaternion operator/= (const Quaternion & r) inline
Quaternion in-place divison.
conj()
__host__ __device__ Quaternion conj () const inline
Conjugate.
Referenced by Quaternion::rotate().
real()
__host__ __device__ float real () const inline
norm()
__host__ __device__ float norm () const inline
The Cayley norm - the square of the Euclidean norm.
Referenced by Quaternion::rotate().
rotate()
__host__ __device__ float3 rotate (fl x, fl y, fl z) const inline
Rotation point (x,y,z) using this quaternion.
Referenced by Transform::backward(), and Quaternion::transform().
transform()
__host__ __device__ float3 transform (fl x, fl y, fl z, float3 center, float3 translate) const inline
Rotate around the provided center and translate.
Referenced by Transform::forward().
inverse()
__host__ __device__ Quaternion inverse () const inline
Return inverse.
Referenced by Transform::backward().
Member Data Documentation
a
fl a protected
Referenced by Quaternion::conj(), Quaternion::inverse(), Quaternion::norm(), Quaternion::operator*(), Quaternion::operator*=(), Quaternion::operator/(), Quaternion::operator/=(), Quaternion::operator==(), and Quaternion::R_component_1().
b
fl b protected
Referenced by Quaternion::conj(), Quaternion::inverse(), Quaternion::norm(), Quaternion::operator*(), Quaternion::operator*=(), Quaternion::operator/(), Quaternion::operator/=(), Quaternion::operator==(), and Quaternion::R_component_2().
c
fl c protected
Referenced by Quaternion::conj(), Quaternion::inverse(), Quaternion::norm(), Quaternion::operator*(), Quaternion::operator*=(), Quaternion::operator/(), Quaternion::operator/=(), Quaternion::operator==(), and Quaternion::R_component_3().
d
fl d protected
Referenced by Quaternion::conj(), Quaternion::inverse(), Quaternion::norm(), Quaternion::operator*(), Quaternion::operator*=(), Quaternion::operator/(), Quaternion::operator/=(), Quaternion::operator==(), and Quaternion::R_component_4().
The documentation for this class was generated from the following file:
quaternion.h