libmolgrid: Transform Class Reference
--- title: Transform Class Reference layout: docs homepage: false hide: true ---
Transform Class Reference
#include <transform.h>
Public Member Functions
Transform ()
Transform (const Quaternion &q, float3 c=make_float3(0, 0, 0), float3 t=make_float3(0, 0, 0))
Transform (float3 c, float random_translate=0.0, bool random_rotate=false)
template<typename Dtype >
void forward (const Grid< Dtype, 2, false > &in, Grid< Dtype, 2, false > &out, bool dotranslate=true) const
void forward (const Example &in, Example &out, bool dotranslate=true) const
void forward (const CoordinateSet &in, CoordinateSet &out, bool dotranslate=true) const
template<typename Dtype >
__host__ void forward (const Grid< Dtype, 2, true > &in, Grid< Dtype, 2, true > &out, bool dotranslate=true) const
template<typename Dtype >
void backward (const Grid< Dtype, 2, false > &in, Grid< Dtype, 2, false > &out, bool dotranslate=true) const
template<typename Dtype >
__host__ void backward (const Grid< Dtype, 2, true > &in, Grid< Dtype, 2, true > &out, bool dotranslate=true) const
const Quaternion & get_quaternion () const
float3 get_rotation_center () const
float3 get_translation () const
void set_quaternion (const Quaternion &q)
void set_rotation_center (float3 c)
void set_translation (float3 t)
bool is_identity () const
Detailed Description
Stateful transformation of Cartesian coordinates.
Stores a center of rotation, quaternion, and translation. Can apply transformation forward or backward, with or without translations.
Constructor & Destructor Documentation
Transform() [1/3]
Transform () inline
Transform() [2/3]
Transform (const Quaternion & q, float3 c = make_float3(0, 0, 0), float3 t = make_float3(0, 0, 0)) inline
Transform() [3/3]
Transform (float3 c, float random_translate = 0.0, bool random_rotate = false)
Member Function Documentation
forward() [1/4]
void forward (const Grid< Dtype, 2, false > & in, Grid< Dtype, 2, false > & out, bool dotranslate = true) const
Referenced by Transform::forward(), and GridMaker::forward().
forward() [2/4]
void forward (const Example & in, Example & out, bool dotranslate = true) const
forward() [3/4]
void forward (const CoordinateSet & in, CoordinateSet & out, bool dotranslate = true) const
forward() [4/4]
__host__ void forward (const Grid< Dtype, 2, true > & in, Grid< Dtype, 2, true > & out, bool dotranslate = true) const
backward() [1/2]
void backward (const Grid< Dtype, 2, false > & in, Grid< Dtype, 2, false > & out, bool dotranslate = true) const
backward() [2/2]
__host__ void backward (const Grid< Dtype, 2, true > & in, Grid< Dtype, 2, true > & out, bool dotranslate = true) const
get_quaternion()
const Quaternion& get_quaternion () const inline
get_rotation_center()
float3 get_rotation_center () const inline
Referenced by GridMaker::forward().
get_translation()
float3 get_translation () const inline
set_quaternion()
void set_quaternion (const Quaternion & q) inline
set_rotation_center()
void set_rotation_center (float3 c) inline
set_translation()
void set_translation (float3 t) inline
is_identity()
bool is_identity () const inline
transformation does not change inputs
The documentation for this class was generated from the following files:
transform.h
transform.cpp