--- title: AtomTyper Class Reference layout: docs homepage: false ---
AtomTyper Class Reference
#include <atom_typer.h>
Public Member Functions
AtomTyper ()
virtual ~AtomTyper ()
virtual unsigned num_types () const
virtual float get_atom_type_vector (OpenBabel::OBAtom *a, std::vector< float > &typ) const
virtual std::pair< int, float > get_atom_type_index (OpenBabel::OBAtom *a) const
virtual std::pair< int, float > get_int_type (int t) const
virtual std::vector< std::string > get_type_names () const
virtual bool is_vector_typer () const
Detailed Description
Base class for all atom typers.
Constructor & Destructor Documentation
AtomTyper()
AtomTyper () inline
~AtomTyper()
virtual ~AtomTyper () inline virtual
Member Function Documentation
num_types()
virtual unsigned num_types () const inline virtual
Reimplemented in CallbackVectorTyper, GninaVectorTyper, MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, GninaIndexTyper, AtomVectorTyper, and AtomIndexTyper.
Referenced by CallbackIndexTyper::get_atom_type_index(), CallbackIndexTyper::get_int_type(), AtomIndexTyper::get_type_radii(), CallbackIndexTyper::get_type_radii(), AtomVectorTyper::get_vector_type_radii(), AtomIndexTyper::~AtomIndexTyper(), AtomVectorTyper::~AtomVectorTyper(), ElementIndexTyper::~ElementIndexTyper(), GninaIndexTyper::~GninaIndexTyper(), and GninaVectorTyper::~GninaVectorTyper().
get_atom_type_vector()
virtual float get_atom_type_vector (OpenBabel::OBAtom * a, std::vector< float > & typ) const inline virtual
Reimplemented in CallbackVectorTyper, GninaVectorTyper, AtomVectorTyper, and AtomIndexTyper.
Referenced by AtomVectorTyper::get_atom_type_index(), and GninaVectorTyper::~GninaVectorTyper().
get_atom_type_index()
virtual std::pair<int,float> get_atom_type_index (OpenBabel::OBAtom * a) const inline virtual
Reimplemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, GninaIndexTyper, AtomVectorTyper, and AtomIndexTyper.
Referenced by AtomIndexTyper::get_atom_type_vector(), ElementIndexTyper::~ElementIndexTyper(), and GninaIndexTyper::~GninaIndexTyper().
get_int_type()
virtual std::pair<int,float> get_int_type (int t) const inline virtual
Reimplemented in MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, GninaIndexTyper, and AtomIndexTyper.
Referenced by AtomIndexTyper::get_atom_type_vector(), ElementIndexTyper::~ElementIndexTyper(), and GninaIndexTyper::~GninaIndexTyper().
get_type_names()
virtual std::vector<std::string> get_type_names () const inline virtual
Reimplemented in CallbackVectorTyper, GninaVectorTyper, MappedAtomIndexTyper< Mapper, Typer >, MappedAtomIndexTyper< FileAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, GninaIndexTyper >, MappedAtomIndexTyper< FileAtomMapper, ElementIndexTyper >, MappedAtomIndexTyper< SubsetAtomMapper, ElementIndexTyper >, CallbackIndexTyper, NullIndexTyper, ElementIndexTyper, GninaIndexTyper, AtomVectorTyper, and AtomIndexTyper.
Referenced by AtomIndexTyper::get_atom_type_vector(), AtomIndexTypeMapper::get_new_type(), AtomVectorTyper::get_vector_type_radii(), ElementIndexTyper::~ElementIndexTyper(), GninaIndexTyper::~GninaIndexTyper(), and GninaVectorTyper::~GninaVectorTyper().
is_vector_typer()
virtual bool is_vector_typer () const inline virtual
Reimplemented in AtomVectorTyper, and AtomIndexTyper.
The documentation for this class was generated from the following file:
atom_typer.h