libmolgrid: GninaIndexTyper Class Reference
--- title: GninaIndexTyper Class Reference layout: docs homepage: false hide: true ---
GninaIndexTyper Class Reference
#include <atom_typer.h>
Classes
struct info
Public Types
enum type {
Hydrogen, PolarHydrogen, AliphaticCarbonXSHydrophobe, AliphaticCarbonXSNonHydrophobe,
AromaticCarbonXSHydrophobe, AromaticCarbonXSNonHydrophobe, Nitrogen, NitrogenXSDonor,
NitrogenXSDonorAcceptor, NitrogenXSAcceptor, Oxygen, OxygenXSDonor,
OxygenXSDonorAcceptor, OxygenXSAcceptor, Sulfur, SulfurAcceptor,
Phosphorus, Fluorine, Chlorine, Bromine,
Iodine, Magnesium, Manganese, Zinc,
Calcium, Iron, GenericMetal, Boron,
NumTypes
}
Public Member Functions
GninaIndexTyper (bool usec=false, const info *d=default_data)
virtual ~GninaIndexTyper ()
virtual unsigned num_types () const
virtual std::pair< int, float > get_atom_type_index (OpenBabel::OBAtom *a) const
virtual std::pair< int, float > get_int_type (int t) const
virtual std::vector< std::string > get_type_names () const
virtual std::vector< float > get_type_radii () const
const info & get_info (int t) const
virtual float get_atom_type_vector (OpenBabel::OBAtom *a, std::vector< float > &typ) const final
virtual bool is_vector_typer () const
Static Public Member Functions
static std::string gnina_type_name (int t)
static void set_names (unsigned ntypes, std::vector< std::string > &type_names, const std::vector< std::string > &names)
Detailed Description
Calculate gnina types.
These are variants of AutoDock4 types.
Member Enumeration Documentation
type
enum type
Enumerator
Hydrogen
PolarHydrogen
AliphaticCarbonXSHydrophobe
AliphaticCarbonXSNonHydrophobe
AromaticCarbonXSHydrophobe
AromaticCarbonXSNonHydrophobe
Nitrogen
NitrogenXSDonor
NitrogenXSDonorAcceptor
NitrogenXSAcceptor
Oxygen
OxygenXSDonor
OxygenXSDonorAcceptor
OxygenXSAcceptor
Sulfur
SulfurAcceptor
Phosphorus
Fluorine
Chlorine
Bromine
Iodine
Magnesium
Manganese
Zinc
Calcium
Iron
GenericMetal
Boron
NumTypes
Constructor & Destructor Documentation
GninaIndexTyper()
GninaIndexTyper (bool usec = false, const info * d = default_data) inline
~GninaIndexTyper()
virtual ~GninaIndexTyper () inline virtual
Member Function Documentation
num_types()
unsigned num_types () const virtual
return number of types
Implements AtomIndexTyper.
get_atom_type_index()
std::pair< int, float > get_atom_type_index (OpenBabel::OBAtom * a) const virtual
return type index of a
return type index and radius of a
Implements AtomIndexTyper.
Referenced by GninaVectorTyper::get_atom_type_vector().
get_int_type()
pair< int, float > get_int_type (int t) const virtual
basically look up the radius of the given gnina type
Implements AtomIndexTyper.
get_type_names()
std::vector< std::string > get_type_names () const virtual
return vector of string representations of types
Implements AtomIndexTyper.
get_type_radii()
std::vector< float > get_type_radii () const virtual
return atomic radius of each type
Reimplemented from AtomIndexTyper.
get_info()
const info& get_info (int t) const inline
return gnina info for a given type
Referenced by GninaVectorTyper::get_atom_type_vector(), and GninaVectorTyper::get_vector_type_radii().
gnina_type_name()
std::string gnina_type_name (int t) static
return name of default gnina type t
get_atom_type_vector()
virtual float get_atom_type_vector (OpenBabel::OBAtom * a, std::vector< float > & typ) const inline final virtual inherited
Reimplemented from AtomTyper.
set_names()
void set_names (unsigned ntypes, std::vector< std::string > & type_names, const std::vector< std::string > & names) static inherited
Referenced by CallbackIndexTyper::CallbackIndexTyper(), and CallbackVectorTyper::CallbackVectorTyper().
is_vector_typer()
virtual bool is_vector_typer () const inline virtual inherited
Reimplemented from AtomTyper.
The documentation for this class was generated from the following files:
atom_typer.h
atom_typer.cpp