--- title: StringCache Class Reference layout: page homepage: false ---
StringCache Class Reference
#include <example.h>
Public Member Functions
const char * get (const std::string &s)
Member Function Documentation
get()
const char* get (const std::string & s) inline
Referenced by CoordCache::CoordCache(), ExampleRef::ExampleRef(), and GroupedExampleRefProvider< Provider >::nextref().
The documentation for this class was generated from the following file:
example.h