libmolgrid: ExampleExtractor Class Reference
--- title: ExampleExtractor Class Reference layout: docs homepage: false hide: true ---
ExampleExtractor Class Reference
#include <example_extractor.h>
Public Member Functions
ExampleExtractor (const ExampleProviderSettings &settings, std::shared_ptr< AtomTyper > t)
ExampleExtractor (const ExampleProviderSettings &settings, std::shared_ptr< AtomTyper > t1, std::shared_ptr< AtomTyper > t2)
ExampleExtractor (const ExampleProviderSettings &settings, const std::vector< std::shared_ptr< AtomTyper > > &typrs, const std::vector< std::string > &molcaches=std::vector< std::string >())
virtual ~ExampleExtractor ()
virtual void extract (const ExampleRef &ref, Example &ex)
virtual size_t num_types () const
virtual size_t num_types (const ExampleRef &ref) const
virtual std::vector< std::string > get_type_names () const
Detailed Description
Converts an ExampleRef to and Example Loads (potentially cached) data and applies atom typers to create coordinate sets. Takes care of in-memory caching (optional) and also supports memory mapped gnina cache files (incurring slight overhead on recalculation of atom types in exchange for substantially less real mem usage).
Can take multiple atom typers, in which case they are applied in order, with the last being repeated.
Constructor & Destructor Documentation
ExampleExtractor() [1/3]
ExampleExtractor (const ExampleProviderSettings & settings, std::shared_ptr< AtomTyper > t) inline
ExampleExtractor() [2/3]
ExampleExtractor (const ExampleProviderSettings & settings, std::shared_ptr< AtomTyper > t1, std::shared_ptr< AtomTyper > t2) inline
ExampleExtractor() [3/3]
ExampleExtractor (const ExampleProviderSettings & settings, const std::vector< std::shared_ptr< AtomTyper > > & typrs, const std::vector< std::string > & molcaches = std::vector<std::string>()) inline
~ExampleExtractor()
virtual ~ExampleExtractor () inline virtual
Member Function Documentation
extract()
void extract (const ExampleRef & ref, Example & ex) virtual
Extract ref into ex.
Referenced by ExampleProvider::next(), and ExampleProvider::next_batch().
num_types() [1/2]
size_t num_types () const virtual
return the number of types (channels) each example will have Note: this is only accurate if types are explicitly setup. Must provide an ExampleRef
Referenced by ExampleProvider::num_types().
num_types() [2/2]
size_t num_types (const ExampleRef & ref) const virtual
get_type_names()
std::vector< std::string > get_type_names () const virtual
return names of types for explicitly typed examples type names are prepended by coordinate set index
Referenced by ExampleProvider::get_type_names().
The documentation for this class was generated from the following files:
example_extractor.h
example_extractor.cpp