libmolgrid: ManagedGridBase< Dtype, NumDims > Class Template Reference
--- title: ManagedGridBase< Dtype, NumDims > Class Template Reference layout: docs homepage: false hide: true ---
ManagedGridBase< Dtype, NumDims > Class Template Reference
#include <managed_grid.h>
Public Types
using gpu_grid_t = Grid< Dtype, NumDims, true >
using cpu_grid_t = Grid< Dtype, NumDims, false >
using type = Dtype
Public Member Functions
const size_t * dimensions () const
size_t dimension (size_t i) const
const size_t * offsets () const
size_t offset (size_t i) const
size_t size () const
void fill_zero ()
template<typename... I>
Dtype & operator() (I... indices)
template<typename... I>
Dtype operator() (I... indices) const
size_t copyTo (cpu_grid_t &dest) const
size_t copyTo (gpu_grid_t &dest) const
size_t copyTo (ManagedGridBase< Dtype, NumDims > &dest) const
size_t copyFrom (const cpu_grid_t &src)
size_t copyFrom (const gpu_grid_t &src)
size_t copyFrom (const ManagedGridBase< Dtype, NumDims > &src)
size_t copyInto (size_t start, const ManagedGridBase< Dtype, NumDims > &src)
template<typename... I, typename = typename std::enable_if<sizeof...(I) == NumDims>::type>
ManagedGrid< Dtype, NumDims > resized (I... sizes)
const gpu_grid_t & gpu () const
gpu_grid_t & gpu ()
const cpu_grid_t & cpu () const
cpu_grid_t & cpu ()
void togpu (bool dotransfer=true) const
void tocpu (bool dotransfer=true) const
bool ongpu () const
bool oncpu () const
operator cpu_grid_t () const
operator cpu_grid_t & ()
operator gpu_grid_t () const
operator gpu_grid_t & ()
const Dtype * data () const
Dtype * data ()
bool operator== (const ManagedGridBase< Dtype, NumDims > &rhs) const
Static Public Attributes
static constexpr size_t N = NumDims
Protected Types
using buffer_data = mgrid_buffer_data< Dtype >
Protected Member Functions
ManagedGridBase ()=default
void alloc_and_set_cpu (size_t sz)
void alloc_and_set_gpu (size_t sz) const
template<typename... I, typename = typename std::enable_if<sizeof...(I) == NumDims>::type>
ManagedGridBase (I... sizes)
void clone_ptrs ()
ManagedGridBase (const ManagedGridBase< Dtype, NumDims+1 > &G, size_t i)
Static Protected Member Functions
static void delete_buffer (void *ptr)
Protected Attributes
gpu_grid_t gpu_grid
cpu_grid_t cpu_grid
std::shared_ptr< Dtype > cpu_ptr
size_t capacity = 0
buffer_data * gpu_info = nullptr
friend ManagedGridBase< Dtype, NumDims-1 >
Detailed Description
template<typename Dtype, std::size_t NumDims>
class libmolgrid::ManagedGridBase< Dtype, NumDims >
ManagedGrid base class.
Member Typedef Documentation
gpu_grid_t
using gpu_grid_t = Grid<Dtype, NumDims, true>
cpu_grid_t
using cpu_grid_t = Grid<Dtype, NumDims, false>
cuda grid type
type
using type = Dtype
buffer_data
using buffer_data = mgrid_buffer_data<Dtype> protected
Constructor & Destructor Documentation
ManagedGridBase() [1/3]
ManagedGridBase () protected default
empty (unusable) grid
ManagedGridBase() [2/3]
ManagedGridBase (I... sizes) inline protected
ManagedGridBase() [3/3]
ManagedGridBase (const ManagedGridBase< Dtype, NumDims+1 > & G, size_t i) inline explicit protected
Member Function Documentation
delete_buffer()
static void delete_buffer (void * ptr) inline static protected
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu().
alloc_and_set_cpu()
void alloc_and_set_cpu (size_t sz) inline protected
Referenced by ManagedGridBase< Dtype, 1 >::clone_ptrs(), and ManagedGridBase< Dtype, 1 >::ManagedGridBase().
alloc_and_set_gpu()
void alloc_and_set_gpu (size_t sz) const inline protected
Referenced by ManagedGridBase< Dtype, 1 >::clone_ptrs(), and ManagedGridBase< Dtype, 1 >::togpu().
clone_ptrs()
void clone_ptrs () inline protected
Referenced by ManagedGrid< Dtype, 1 >::clone().
dimensions()
const size_t* dimensions () const inline
dimensions along each axis
dimension()
size_t dimension (size_t i) const inline
dimensions along specified axis
offsets()
const size_t* offsets () const inline
offset for each dimension, all indexing calculations use this
offset()
size_t offset (size_t i) const inline
offset for each dimension, all indexing calculations use this
Referenced by ManagedGridBase< Dtype, 1 >::copyInto(), and ManagedGridBase< Dtype, 1 >::togpu().
size()
size_t size () const inline
number of elements in grid
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom(), ManagedGridBase< Dtype, 1 >::copyInto(), ManagedGridBase< Dtype, 1 >::copyTo(), ManagedGridBase< Dtype, 1 >::ManagedGridBase(), and ManagedGridBase< Dtype, 1 >::resized().
fill_zero()
void fill_zero () inline
set contents to zero
operator()() [1/2]
Dtype& operator() (I... indices) inline
Initializer list indexing.
operator()() [2/2]
Dtype operator() (I... indices) const inline
copyTo() [1/3]
size_t copyTo (cpu_grid_t & dest) const inline
Copy data into dest. Should be same size, but will narrow if needed.
Referenced by ManagedGridBase< Dtype, 1 >::copyTo(), and ManagedGridBase< Dtype, 1 >::resized().
copyTo() [2/3]
size_t copyTo (gpu_grid_t & dest) const inline
Copy data into dest. Should be same size, but will narrow if needed.
copyTo() [3/3]
size_t copyTo (ManagedGridBase< Dtype, NumDims > & dest) const inline
Copy data into dest. Should be same size, but will narrow if needed.
copyFrom() [1/3]
size_t copyFrom (const cpu_grid_t & src) inline
Copy data from src. Should be same size, but will narrow if needed.
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom().
copyFrom() [2/3]
size_t copyFrom (const gpu_grid_t & src) inline
Copy data from src. Should be same size, but will narrow if needed.
copyFrom() [3/3]
size_t copyFrom (const ManagedGridBase< Dtype, NumDims > & src) inline
Copy data from src. Should be same size, but will narrow if needed.
copyInto()
size_t copyInto (size_t start, const ManagedGridBase< Dtype, NumDims > & src) inline
Copy data from src into this starting at start. Should be same size, but will narrow if needed.
resized()
ManagedGrid<Dtype, NumDims> resized (I... sizes) inline
Return a grid in the specified shape that attempts to reuse the memory of this grid. Memory will be allocated if needed. Data will be truncated/copied as needed. DANGER! The returned grid may or may not mirror this grid depending on the shape. This function is provided so code can be optimized to avoid unnecessary allocations and should be used carefully.
gpu() [1/2]
const gpu_grid_t& gpu () const inline
Return GPU Grid view. Host code should not access the grid until the GPU code is complete.
Referenced by ManagedGridBase< Dtype, 1 >::operator gpu_grid_t(), and ManagedGridBase< Dtype, 1 >::operator gpu_grid_t &().
gpu() [2/2]
gpu_grid_t& gpu () inline
cpu() [1/2]
const cpu_grid_t& cpu () const inline
Return CPU Grid view. GPU code should no longer access this memory.
Referenced by ManagedGridBase< Dtype, 1 >::data(), ManagedGridBase< Dtype, 1 >::operator cpu_grid_t(), and ManagedGridBase< Dtype, 1 >::operator cpu_grid_t &().
cpu() [2/2]
cpu_grid_t& cpu () inline
togpu()
void togpu (bool dotransfer = true) const inline
Transfer data to GPU.
Referenced by ManagedGridBase< Dtype, 1 >::gpu(), and ManagedGridBase< Dtype, 1 >::ongpu().
tocpu()
void tocpu (bool dotransfer = true) const inline
Transfer data to CPU. If not dotransfer, data is not copied back.
Referenced by ManagedGridBase< Dtype, 1 >::cpu(), ManagedGridBase< Dtype, 1 >::data(), and ManagedGridBase< Dtype, 1 >::operator()().
ongpu()
bool ongpu () const inline
Return true if memory is currently on GPU.
Referenced by ManagedGridBase< Dtype, 1 >::copyFrom(), ManagedGridBase< Dtype, 1 >::copyInto(), ManagedGridBase< Dtype, 1 >::copyTo(), ManagedGridBase< Dtype, 1 >::fill_zero(), ManagedGridBase< Dtype, 1 >::resized(), and ManagedGridBase< Dtype, 1 >::tocpu().
oncpu()
bool oncpu () const inline
Return true if memory is currently on CPU.
Referenced by ManagedGridBase< Dtype, 1 >::togpu().
operator cpu_grid_t()
operator cpu_grid_t () const inline
operator cpu_grid_t &()
operator cpu_grid_t & () inline
operator gpu_grid_t()
operator gpu_grid_t () const inline
operator gpu_grid_t &()
operator gpu_grid_t & () inline
data() [1/2]
const Dtype* data () const inline
Return pointer to CPU data.
Referenced by ManagedGridBase< Dtype, 1 >::copyInto(), and ManagedGridBase< Dtype, 1 >::delete_buffer().
data() [2/2]
Dtype* data () inline
operator==()
bool operator== (const ManagedGridBase< Dtype, NumDims > & rhs) const inline
Member Data Documentation
N
constexpr size_t N = NumDims static constexpr
gpu_grid
gpu_grid_t gpu_grid mutable protected
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_gpu(), ManagedGridBase< Dtype, 1 >::copyFrom(), ManagedGridBase< Dtype, 1 >::copyInto(), ManagedGridBase< Dtype, 1 >::copyTo(), ManagedGridBase< Dtype, 1 >::fill_zero(), ManagedGridBase< Dtype, 1 >::gpu(), ManagedGridBase< Dtype, 1 >::ongpu(), and ManagedGridBase< Dtype, 1 >::togpu().
cpu_grid
cpu_grid_t cpu_grid protected
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu(), ManagedGridBase< Dtype, 1 >::copyFrom(), ManagedGridBase< Dtype, 1 >::copyInto(), ManagedGridBase< Dtype, 1 >::copyTo(), ManagedGridBase< Dtype, 1 >::cpu(), ManagedGridBase< Dtype, 1 >::dimension(), ManagedGridBase< Dtype, 1 >::dimensions(), ManagedGridBase< Dtype, 1 >::fill_zero(), ManagedGridBase< Dtype, 1 >::offset(), ManagedGridBase< Dtype, 1 >::offsets(), ManagedGridBase< Dtype, 1 >::operator()(), ManagedGridBase< Dtype, 1 >::size(), and ManagedGridBase< Dtype, 1 >::togpu().
cpu_ptr
std::shared_ptr<Dtype> cpu_ptr protected
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu(), ManagedGridBase< Dtype, 1 >::clone_ptrs(), ManagedGridBase< Dtype, 1 >::ManagedGridBase(), ManagedGridBase< Dtype, 1 >::operator==(), ManagedGridBase< Dtype, 1 >::resized(), ManagedGridBase< Dtype, 1 >::tocpu(), and ManagedGridBase< Dtype, 1 >::togpu().
capacity
size_t capacity = 0 protected
Referenced by ManagedGridBase< Dtype, 1 >::clone_ptrs(), ManagedGridBase< Dtype, 1 >::ManagedGridBase(), ManagedGridBase< Dtype, 1 >::resized(), ManagedGridBase< Dtype, 1 >::tocpu(), and ManagedGridBase< Dtype, 1 >::togpu().
gpu_info
buffer_data* gpu_info = nullptr mutable protected
Referenced by ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu(), ManagedGridBase< Dtype, 1 >::alloc_and_set_gpu(), ManagedGridBase< Dtype, 1 >::clone_ptrs(), ManagedGridBase< Dtype, 1 >::ManagedGridBase(), ManagedGridBase< Dtype, 1 >::oncpu(), ManagedGridBase< Dtype, 1 >::ongpu(), ManagedGridBase< Dtype, 1 >::resized(), ManagedGridBase< Dtype, 1 >::tocpu(), and ManagedGridBase< Dtype, 1 >::togpu().
ManagedGridBase< Dtype, NumDims-1 >
friend ManagedGridBase< Dtype, NumDims-1 > protected
The documentation for this class was generated from the following file:
managed_grid.h