--- title: GridMaker Class Reference layout: page homepage: false ---
GridMaker Class Reference
#include <grid_maker.h>
Public Member Functions
GridMaker (float res=0, float d=0, bool bin=false, bool rti=false, float rscale=1.0, float grm=1.0)
virtual ~GridMaker ()
void initialize (float res, float d, bool bin=false, float rscale=1.0, float grm=1.0)
float3 get_grid_dims () const
CUDA_CALLABLE_MEMBER float get_resolution () const
CUDA_CALLABLE_MEMBER void set_resolution (float res)
CUDA_CALLABLE_MEMBER float get_dimension () const
CUDA_CALLABLE_MEMBER void set_dimension (float d)
CUDA_CALLABLE_MEMBER unsigned get_first_dim () const
CUDA_CALLABLE_MEMBER bool get_binary () const
CUDA_CALLABLE_MEMBER void set_binary (bool b)
CUDA_CALLABLE_MEMBER bool get_radii_type_indexed () const
CUDA_CALLABLE_MEMBER void set_radii_type_indexed (bool b)
CUDA_CALLABLE_MEMBER float get_radiusmultiple () const
CUDA_CALLABLE_MEMBER float3 get_grid_origin (const float3 &grid_center) const
template<typename Dtype >
void forward (float3 grid_center, const CoordinateSet &in, Grid< Dtype, 4, false > &out) const
template<typename Dtype >
void forward (float3 grid_center, const CoordinateSet &in, Grid< Dtype, 4, true > &out) const
template<typename Dtype , bool isCUDA>
void forward (const Example &in, const Transform &transform, Grid< Dtype, 4, isCUDA > &out) const
template<typename Dtype , bool isCUDA>
void forward (const Example &in, Grid< Dtype, 4, isCUDA > &out, float random_translation=0.0, bool random_rotation=false, const float3 &center=make_float3(INFINITY, INFINITY, INFINITY)) const
template<typename Dtype , bool isCUDA>
void forward (const std::vector< Example > &in, Grid< Dtype, 5, isCUDA > &out, float random_translation=0.0, bool random_rotation=false) const
template<typename Dtype >
void forward (float3 grid_center, const Grid< float, 2, false > &coords, const Grid< float, 1, false > &type_index, const Grid< float, 1, false > &radii, Grid< Dtype, 4, false > &out) const
template<typename Dtype >
void forward (float3 grid_center, const Grid< float, 2, true > &coords, const Grid< float, 1, true > &type_index, const Grid< float, 1, true > &radii, Grid< Dtype, 4, true > &out) const
template<typename Dtype , bool TypesFromRadii = false>
void forward (float3 grid_center, const Grid< float, 2, false > &coords, const Grid< float, 2, false > &type_vector, const Grid< float, 1, false > &radii, Grid< Dtype, 4, false > &out) const
template<typename Dtype >
void forward (float3 grid_center, const Grid< float, 2, true > &coords, const Grid< float, 2, true > &type_vector, const Grid< float, 1, true > &radii, Grid< Dtype, 4, true > &out) const
template<typename Dtype >
void backward (float3 grid_center, const CoordinateSet &in, const Grid< Dtype, 4, false > &diff, Grid< Dtype, 2, false > &atomic_gradients, Grid< Dtype, 2, false > &type_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const CoordinateSet &in, const Grid< Dtype, 4, false > &diff, Grid< Dtype, 2, false > &atomic_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const CoordinateSet &in, const Grid< Dtype, 4, true > &diff, Grid< Dtype, 2, true > &atomic_gradients, Grid< Dtype, 2, true > &type_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const CoordinateSet &in, const Grid< Dtype, 4, true > &diff, Grid< Dtype, 2, true > &atomic_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const Grid< float, 2, false > &coords, const Grid< float, 1, false > &type_index, const Grid< float, 1, false > &radii, const Grid< Dtype, 4, false > &diff, Grid< Dtype, 2, false > &atom_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const Grid< float, 2, true > &coords, const Grid< float, 1, true > &type_index, const Grid< float, 1, true > &radii, const Grid< Dtype, 4, true > &grid, Grid< Dtype, 2, true > &atom_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const Grid< float, 2, false > &coords, const Grid< float, 2, false > &type_vectors, const Grid< float, 1, false > &radii, const Grid< Dtype, 4, false > &diff, Grid< Dtype, 2, false > &atom_gradients, Grid< Dtype, 2, false > &type_gradients) const
template<typename Dtype >
void backward (float3 grid_center, const Grid< float, 2, true > &coords, const Grid< float, 2, true > &type_vectors, const Grid< float, 1, true > &radii, const Grid< Dtype, 4, true > &grid, Grid< Dtype, 2, true > &atom_gradients, Grid< Dtype, 2, true > &type_gradients) const
template<typename Dtype >
void backward_relevance (float3 grid_center, const CoordinateSet &in, const Grid< Dtype, 4, false > &density, const Grid< Dtype, 4, false > &diff, Grid< Dtype, 1, false > &relevance) const
template<typename Dtype >
void backward_relevance (float3 grid_center, const CoordinateSet &in, const Grid< Dtype, 4, true > &density, const Grid< Dtype, 4, true > &diff, Grid< Dtype, 1, true > &relevance) const
template<typename Dtype >
void backward_relevance (float3 grid_center, const Grid< float, 2, false > &coords, const Grid< float, 1, false > &type_index, const Grid< float, 1, false > &radii, const Grid< Dtype, 4, false > &density, const Grid< Dtype, 4, false > &diff, Grid< Dtype, 1, false > &relevance) const
template<typename Dtype >
void backward_relevance (float3 grid_center, const Grid< float, 2, true > &coords, const Grid< float, 1, true > &type_index, const Grid< float, 1, true > &radii, const Grid< Dtype, 4, true > &density, const Grid< Dtype, 4, true > &diff, Grid< Dtype, 1, true > &relevance) const
template<typename Dtype , bool Binary>
CUDA_DEVICE_MEMBER void set_atoms (unsigned natoms, float3 grid_origin, const float3 *coords, const float *tindex, const float *radii, Dtype *out)
template<typename Dtype , bool Binary, bool RadiiFromTypes>
CUDA_DEVICE_MEMBER void set_atoms (unsigned natoms, float3 grid_origin, const float3 *coords, const float *type_vec, unsigned ntypes, const float *radii, Dtype *out)
template<typename Dtype >
float3 calc_atom_gradient_cpu (const float3 &grid_origin, const Grid1f &coord, const Grid< Dtype, 3, false > &diff, float radius) const
template<typename Dtype >
float calc_type_gradient_cpu (const float3 &grid_origin, const Grid1f &coord, const Grid< Dtype, 3, false > &diff, float radius) const
template<typename Dtype >
float calc_atom_relevance_cpu (const float3 &grid_origin, const Grid1f &coord, const Grid< Dtype, 3, false > &density, const Grid< Dtype, 3, false > &diff, float radius) const
CUDA_CALLABLE_MEMBER uint2 get_bounds_1d (const float grid_origin, float coord, float densityrad) const
template<bool Binary>
CUDA_CALLABLE_MEMBER float calc_point (float ax, float ay, float az, float ar, const float3 &grid_coords) const
CUDA_CALLABLE_MEMBER void accumulate_atom_gradient (float ax, float ay, float az, float x, float y, float z, float radius, float gridval, float3 &agrad) const
Protected Member Functions
template<typename Dtype , bool isCUDA>
void check_index_args (const Grid< float, 2, isCUDA > &coords, const Grid< float, 1, isCUDA > &type_index, const Grid< float, 1, isCUDA > &radii, Grid< Dtype, 4, isCUDA > &out) const
template<typename Dtype , bool isCUDA>
void check_vector_args (const Grid< float, 2, isCUDA > &coords, const Grid< float, 2, isCUDA > &type_vector, const Grid< float, 1, isCUDA > &radii, Grid< Dtype, 4, isCUDA > &out) const
Protected Attributes
float resolution = 0.5
float dimension = 0
float radius_scale = 1.0
float gaussian_radius_multiple = 1.0
float final_radius_multiple = 1.5
float A
float B
float C
float D
float E
bool binary = false
bool radii_type_indexed = false
unsigned dim
Friends
template<typename Dtype >
__global__ friend void set_atom_gradients (GridMaker G, float3 grid_center, Grid2fCUDA coords, Grid1fCUDA type_index, Grid1fCUDA radii, Grid< Dtype, 4, true > grid, Grid< Dtype, 2, true > atom_gradients)
template<typename Dtype , bool RadiiFromTypes>
__global__ friend void set_atom_type_gradients (GridMaker G, float3 grid_origin, Grid2fCUDA coords, Grid2fCUDA type_vector, unsigned ntypes, Grid1fCUDA radii, Grid< Dtype, 4, true > grid, Grid< Dtype, 2, true > atom_gradients, Grid< Dtype, 2, true > type_gradients)
template<typename Dtype >
__global__ friend void set_atom_relevance (GridMaker G, float3 grid_origin, Grid2fCUDA coords, Grid1fCUDA type_index, Grid1fCUDA radii, Grid< Dtype, 4, true > densitygrid, Grid< Dtype, 4, true > diffgrid, Grid< Dtype, 1, true > relevance)
Detailed Description
Populates a grid with atom density values that correspond to atoms in a CoordinateSet and accumulates atomic gradients from the grid gradients. It stores state about universal grid settings. In functions that map from atomic coordinates to grids and vice versa (e.g. forward and backward), it must be passed the grid_center (which may have changed due to transformations performed directly on the atom coordinates externally to this class)
Constructor & Destructor Documentation
GridMaker()
GridMaker (float res = 0, float d = 0, bool bin = false, bool rti = false, float rscale = 1.0, float grm = 1.0) inline
~GridMaker()
virtual ~GridMaker () inline virtual
Member Function Documentation
check_index_args()
template void check_index_args (const Grid< float, 2, isCUDA > & coords, const Grid< float, 1, isCUDA > & type_index, const Grid< float, 1, isCUDA > & radii, Grid< Dtype, 4, isCUDA > & out) const protected
grid width in points
Referenced by GridMaker::forward().
check_vector_args()
template void check_vector_args (const Grid< float, 2, isCUDA > & coords, const Grid< float, 2, isCUDA > & type_vector, const Grid< float, 1, isCUDA > & radii, Grid< Dtype, 4, isCUDA > & out) const protected
Referenced by GridMaker::forward().
initialize()
void initialize (float res, float d, bool bin = false, float rscale = 1.0, float grm = 1.0)
Initialize grid settings.
Parameters
[in] res resolution of grid in Angstroms
[in] d dimension of cubic grid side in Angstroms
[in] bin boolean indicating if binary density should be used
[in] rscale scaling factor to be uniformly applied to all input radii
[in] grm gaussian radius multiplier - cutoff point for switching from Gaussian density to quadratic
Referenced by GridMaker::GridMaker(), and GridMaker::~GridMaker().
get_grid_dims()
float3 get_grid_dims () const inline
return spatial dimensions of grid
get_resolution()
CUDA_CALLABLE_MEMBER float get_resolution () const inline
return resolution in Angstroms
set_resolution()
CUDA_CALLABLE_MEMBER void set_resolution (float res) inline
set resolution in Angstroms
get_dimension()
CUDA_CALLABLE_MEMBER float get_dimension () const inline
get dimension in Angstroms
set_dimension()
CUDA_CALLABLE_MEMBER void set_dimension (float d) inline
set dimension in Angstroms
get_first_dim()
CUDA_CALLABLE_MEMBER unsigned get_first_dim () const inline
get_binary()
CUDA_CALLABLE_MEMBER bool get_binary () const inline
return if density is binary
set_binary()
CUDA_CALLABLE_MEMBER void set_binary (bool b) inline
set if density is binary
get_radii_type_indexed()
CUDA_CALLABLE_MEMBER bool get_radii_type_indexed () const inline
return if radius array should be indexed by type id (for vector types)
set_radii_type_indexed()
CUDA_CALLABLE_MEMBER void set_radii_type_indexed (bool b) inline
set if radius array should be indexed by type id, not atom
get_radiusmultiple()
CUDA_CALLABLE_MEMBER float get_radiusmultiple () const inline
return multiplier of radius where density goes to zero
get_grid_origin()
float3 get_grid_origin (const float3 & grid_center) const
Use externally specified grid_center to determine where grid begins. Used for translating between cartesian coords and grids.
Parameters
[in] grid center
[out] grid bounds
Referenced by GridMaker::backward(), GridMaker::backward_relevance(), GridMaker::forward(), and GridMaker::get_radiusmultiple().
forward() [1/9]
void forward (float3 grid_center, const CoordinateSet & in, Grid< Dtype, 4, false > & out) const inline
Referenced by GridMaker::forward().
forward() [2/9]
void forward (float3 grid_center, const CoordinateSet & in, Grid< Dtype, 4, true > & out) const inline
forward() [3/9]
void forward (const Example & in, const Transform & transform, Grid< Dtype, 4, isCUDA > & out) const
forward() [4/9]
void forward (const Example & in, Grid< Dtype, 4, isCUDA > & out, float random_translation = 0.0, bool random_rotation = false, const float3 & center = make_float3(INFINITY, INFINITY, INFINITY)) const
forward() [5/9]
void forward (const std::vector< Example > & in, Grid< Dtype, 5, isCUDA > & out, float random_translation = 0.0, bool random_rotation = false) const inline
forward() [6/9]
void forward (float3 grid_center, const Grid< float, 2, false > & coords, const Grid< float, 1, false > & type_index, const Grid< float, 1, false > & radii, Grid< Dtype, 4, false > & out) const
forward() [7/9]
void forward (float3 grid_center, const Grid< float, 2, true > & coords, const Grid< float, 1, true > & type_index, const Grid< float, 1, true > & radii, Grid< Dtype, 4, true > & out) const
forward() [8/9]
void forward (float3 grid_center, const Grid< float, 2, false > & coords, const Grid< float, 2, false > & type_vector, const Grid< float, 1, false > & radii, Grid< Dtype, 4, false > & out) const
forward() [9/9]
void forward (float3 grid_center, const Grid< float, 2, true > & coords, const Grid< float, 2, true > & type_vector, const Grid< float, 1, true > & radii, Grid< Dtype, 4, true > & out) const
backward() [1/8]
void backward (float3 grid_center, const CoordinateSet & in, const Grid< Dtype, 4, false > & diff, Grid< Dtype, 2, false > & atomic_gradients, Grid< Dtype, 2, false > & type_gradients) const inline
Referenced by GridMaker::backward().
backward() [2/8]
void backward (float3 grid_center, const CoordinateSet & in, const Grid< Dtype, 4, false > & diff, Grid< Dtype, 2, false > & atomic_gradients) const inline
backward() [3/8]
void backward (float3 grid_center, const CoordinateSet & in, const Grid< Dtype, 4, true > & diff, Grid< Dtype, 2, true > & atomic_gradients, Grid< Dtype, 2, true > & type_gradients) const inline
backward() [4/8]
void backward (float3 grid_center, const CoordinateSet & in, const Grid< Dtype, 4, true > & diff, Grid< Dtype, 2, true > & atomic_gradients) const inline
backward() [5/8]
void backward (float3 grid_center, const Grid< float, 2, false > & coords, const Grid< float, 1, false > & type_index, const Grid< float, 1, false > & radii, const Grid< Dtype, 4, false > & diff, Grid< Dtype, 2, false > & atom_gradients) const
backward() [6/8]
void backward (float3 grid_center, const Grid< float, 2, true > & coords, const Grid< float, 1, true > & type_index, const Grid< float, 1, true > & radii, const Grid< Dtype, 4, true > & grid, Grid< Dtype, 2, true > & atom_gradients) const
backward() [7/8]
void backward (float3 grid_center, const Grid< float, 2, false > & coords, const Grid< float, 2, false > & type_vectors, const Grid< float, 1, false > & radii, const Grid< Dtype, 4, false > & diff, Grid< Dtype, 2, false > & atom_gradients, Grid< Dtype, 2, false > & type_gradients) const
backward() [8/8]
void backward (float3 grid_center, const Grid< float, 2, true > & coords, const Grid< float, 2, true > & type_vectors, const Grid< float, 1, true > & radii, const Grid< Dtype, 4, true > & grid, Grid< Dtype, 2, true > & atom_gradients, Grid< Dtype, 2, true > & type_gradients) const
backward_relevance() [1/4]
void backward_relevance (float3 grid_center, const CoordinateSet & in, const Grid< Dtype, 4, false > & density, const Grid< Dtype, 4, false > & diff, Grid< Dtype, 1, false > & relevance) const inline
Referenced by GridMaker::backward_relevance().
backward_relevance() [2/4]
void backward_relevance (float3 grid_center, const CoordinateSet & in, const Grid< Dtype, 4, true > & density, const Grid< Dtype, 4, true > & diff, Grid< Dtype, 1, true > & relevance) const inline
backward_relevance() [3/4]
void backward_relevance (float3 grid_center, const Grid< float, 2, false > & coords, const Grid< float, 1, false > & type_index, const Grid< float, 1, false > & radii, const Grid< Dtype, 4, false > & density, const Grid< Dtype, 4, false > & diff, Grid< Dtype, 1, false > & relevance) const
backward_relevance() [4/4]
void backward_relevance (float3 grid_center, const Grid< float, 2, true > & coords, const Grid< float, 1, true > & type_index, const Grid< float, 1, true > & radii, const Grid< Dtype, 4, true > & density, const Grid< Dtype, 4, true > & diff, Grid< Dtype, 1, true > & relevance) const
set_atoms() [1/2]
CUDA_DEVICE_MEMBER void set_atoms (unsigned natoms, float3 grid_origin, const float3 * coords, const float * tindex, const float * radii, Dtype * out)
Referenced by GridMaker::backward_relevance().
set_atoms() [2/2]
CUDA_DEVICE_MEMBER void set_atoms (unsigned natoms, float3 grid_origin, const float3 * coords, const float * type_vec, unsigned ntypes, const float * radii, Dtype * out)
calc_atom_gradient_cpu()
float3 calc_atom_gradient_cpu (const float3 & grid_origin, const Grid1f & coord, const Grid< Dtype, 3, false > & diff, float radius) const
Referenced by GridMaker::backward(), and GridMaker::backward_relevance().
calc_type_gradient_cpu()
float calc_type_gradient_cpu (const float3 & grid_origin, const Grid1f & coord, const Grid< Dtype, 3, false > & diff, float radius) const
Referenced by GridMaker::backward(), and GridMaker::backward_relevance().
calc_atom_relevance_cpu()
float calc_atom_relevance_cpu (const float3 & grid_origin, const Grid1f & coord, const Grid< Dtype, 3, false > & density, const Grid< Dtype, 3, false > & diff, float radius) const
Referenced by GridMaker::backward_relevance().
get_bounds_1d()
CUDA_CALLABLE_MEMBER uint2 get_bounds_1d (const float grid_origin, float coord, float densityrad) const
Referenced by GridMaker::backward_relevance(), GridMaker::calc_atom_gradient_cpu(), GridMaker::calc_atom_relevance_cpu(), GridMaker::calc_type_gradient_cpu(), and GridMaker::forward().
calc_point()
CUDA_CALLABLE_MEMBER float calc_point (float ax, float ay, float az, float ar, const float3 & grid_coords) const
Referenced by GridMaker::backward_relevance().
accumulate_atom_gradient()
CUDA_CALLABLE_MEMBER void accumulate_atom_gradient (float ax, float ay, float az, float x, float y, float z, float radius, float gridval, float3 & agrad) const
Referenced by GridMaker::backward_relevance(), and GridMaker::calc_atom_gradient_cpu().
Friends And Related Function Documentation
set_atom_gradients
__global__ friend void set_atom_gradients (GridMaker G, float3 grid_center, Grid2fCUDA coords, Grid1fCUDA type_index, Grid1fCUDA radii, Grid< Dtype, 4, true > grid, Grid< Dtype, 2, true > atom_gradients) friend
Referenced by GridMaker::backward_relevance().
set_atom_type_gradients
__global__ friend void set_atom_type_gradients (GridMaker G, float3 grid_origin, Grid2fCUDA coords, Grid2fCUDA type_vector, unsigned ntypes, Grid1fCUDA radii, Grid< Dtype, 4, true > grid, Grid< Dtype, 2, true > atom_gradients, Grid< Dtype, 2, true > type_gradients) friend
Referenced by GridMaker::backward_relevance().
set_atom_relevance
__global__ friend void set_atom_relevance (GridMaker G, float3 grid_origin, Grid2fCUDA coords, Grid1fCUDA type_index, Grid1fCUDA radii, Grid< Dtype, 4, true > densitygrid, Grid< Dtype, 4, true > diffgrid, Grid< Dtype, 1, true > relevance) friend
Referenced by GridMaker::backward_relevance().
Member Data Documentation
resolution
float resolution = 0.5 protected
Referenced by GridMaker::calc_atom_gradient_cpu(), GridMaker::calc_atom_relevance_cpu(), GridMaker::calc_type_gradient_cpu(), GridMaker::forward(), GridMaker::get_resolution(), and GridMaker::initialize().
dimension
float dimension = 0 protected
grid spacing
Referenced by GridMaker::get_dimension(), GridMaker::get_grid_origin(), and GridMaker::initialize().
radius_scale
float radius_scale = 1.0 protected
grid side length in Angstroms
Referenced by GridMaker::calc_atom_gradient_cpu(), GridMaker::calc_atom_relevance_cpu(), GridMaker::calc_type_gradient_cpu(), GridMaker::forward(), and GridMaker::initialize().
gaussian_radius_multiple
float gaussian_radius_multiple = 1.0 protected
pre-multiplier for radius; simplest way to change size of atoms
Referenced by GridMaker::initialize().
final_radius_multiple
float final_radius_multiple = 1.5 protected
multiple of atomic radius that gaussian function extends to this is not set by the user, for G=gaussian_radius_multiple this is ${1+2G^2}{2G}$
Referenced by GridMaker::calc_atom_gradient_cpu(), GridMaker::calc_atom_relevance_cpu(), GridMaker::calc_type_gradient_cpu(), GridMaker::forward(), GridMaker::get_radiusmultiple(), and GridMaker::initialize().
A
float A protected
Referenced by GridMaker::initialize().
B
float B protected
Referenced by GridMaker::initialize().
C
float C protected
Referenced by GridMaker::initialize().
D
float D protected
Referenced by GridMaker::initialize().
E
float E protected
Referenced by GridMaker::initialize().
binary
bool binary = false protected
Referenced by GridMaker::calc_atom_relevance_cpu(), GridMaker::calc_type_gradient_cpu(), GridMaker::forward(), GridMaker::get_binary(), and GridMaker::initialize().
radii_type_indexed
bool radii_type_indexed = false protected
use binary occupancy instead of real-valued atom density
Referenced by GridMaker::backward(), GridMaker::check_vector_args(), GridMaker::forward(), and GridMaker::get_radii_type_indexed().
dim
unsigned dim protected
Referenced by GridMaker::backward(), GridMaker::check_index_args(), GridMaker::check_vector_args(), GridMaker::forward(), GridMaker::get_first_dim(), and GridMaker::initialize().
The documentation for this class was generated from the following files:
grid_maker.h
grid_maker.cpp