--- title: ExampleRefProvider Class Reference layout: docs homepage: false ---
ExampleRefProvider Class Reference abstract
#include <exampleref_providers.h>
Public Member Functions
ExampleRefProvider ()
ExampleRefProvider (const ExampleProviderSettings &settings)
virtual void addref (const ExampleRef &ex)=0
virtual void setup ()=0
virtual void nextref (ExampleRef &ex)=0
virtual unsigned size () const =0
virtual ~ExampleRefProvider ()
virtual bool has_group () const
virtual void check_batch_size (unsigned bsize) const
virtual size_t num_labels () const =0
virtual int populate (std::istream &lines, int numlabels)
Detailed Description
abstract class for storing training example references
Constructor & Destructor Documentation
ExampleRefProvider() [1/2]
ExampleRefProvider () inline
ExampleRefProvider() [2/2]
ExampleRefProvider (const ExampleProviderSettings & settings) inline
~ExampleRefProvider()
virtual ~ExampleRefProvider () inline virtual
Member Function Documentation
addref()
virtual void addref (const ExampleRef & ex) pure virtual
Implemented in GroupedExampleRefProvider< Provider >, ValueStratifiedExampleRefProfider< Provider >, ReceptorStratifiedExampleRefProvider< Provider, K >, SamplingExampleRefProvider< Provider1, Provider2 >, BalancedExampleRefProvider, and UniformExampleRefProvider.
Referenced by BalancedExampleRefProvider::BalancedExampleRefProvider(), ExampleRefProvider::ExampleRefProvider(), and UniformExampleRefProvider::UniformExampleRefProvider().
setup()
virtual void setup () pure virtual
Implemented in GroupedExampleRefProvider< Provider >, ValueStratifiedExampleRefProfider< Provider >, ReceptorStratifiedExampleRefProvider< Provider, K >, ReceptorStratifiedExampleRefProvider< Provider, K >, SamplingExampleRefProvider< Provider1, Provider2 >, BalancedExampleRefProvider, UniformExampleRefProvider, and ReceptorStratifiedExampleRefProvider< Provider, K >.
Referenced by ExampleRefProvider::ExampleRefProvider(), UniformExampleRefProvider::num_labels(), and BalancedExampleRefProvider::num_labels().
nextref()
virtual void nextref (ExampleRef & ex) pure virtual
Implemented in GroupedExampleRefProvider< Provider >, ValueStratifiedExampleRefProfider< Provider >, ReceptorStratifiedExampleRefProvider< Provider, K >, SamplingExampleRefProvider< Provider1, Provider2 >, BalancedExampleRefProvider, and UniformExampleRefProvider.
Referenced by ExampleRefProvider::ExampleRefProvider(), UniformExampleRefProvider::num_labels(), and BalancedExampleRefProvider::num_labels().
size()
virtual unsigned size () const pure virtual
Implemented in GroupedExampleRefProvider< Provider >, ValueStratifiedExampleRefProfider< Provider >, ReceptorStratifiedExampleRefProvider< Provider, K >, SamplingExampleRefProvider< Provider1, Provider2 >, BalancedExampleRefProvider, and UniformExampleRefProvider.
Referenced by GroupedExampleRefProvider< Provider >::addref(), ExampleRefProvider::ExampleRefProvider(), ReceptorStratifiedExampleRefProvider< Provider, K >::nextref(), ReceptorStratifiedExampleRefProvider< Provider, K >::num_labels(), ValueStratifiedExampleRefProfider< Provider >::num_labels(), and ValueStratifiedExampleRefProfider< Provider >::setup().
has_group()
virtual bool has_group () const inline virtual
Reimplemented in GroupedExampleRefProvider< Provider >.
check_batch_size()
virtual void check_batch_size (unsigned bsize) const inline virtual
has group field
Reimplemented in GroupedExampleRefProvider< Provider >.
num_labels()
virtual size_t num_labels () const pure virtual
return number of labels in an example
if provider has predetermined batch size
Implemented in GroupedExampleRefProvider< Provider >, ValueStratifiedExampleRefProfider< Provider >, ReceptorStratifiedExampleRefProvider< Provider, K >, SamplingExampleRefProvider< Provider1, Provider2 >, BalancedExampleRefProvider, and UniformExampleRefProvider.
Referenced by ExampleRefProvider::check_batch_size(), ReceptorStratifiedExampleRefProvider< Provider, K >::num_labels(), and ValueStratifiedExampleRefProfider< Provider >::num_labels().
populate()
int populate (std::istream & lines, int numlabels) virtual
read in all the example refs from lines, but does not setup
Referenced by ExampleRefProvider::check_batch_size().
The documentation for this class was generated from the following files:
exampleref_providers.h
exampleref_providers.cpp