libmolgrid: libmolgrid Namespace Reference
--- title: libmolgrid Namespace Reference layout: docs homepage: false hide: true ---
libmolgrid Namespace Reference
Classes
class AtomIndexTypeMapper
class AtomIndexTyper
class AtomTyper
class AtomVectorTyper
class BalancedExampleRefProvider
class CallbackIndexTyper
class CallbackVectorTyper
class CartesianGrid
class CoordCache
struct CoordinateSet
class ElementIndexTyper
struct Example
class ExampleExtractor
class ExampleProvider
struct ExampleProviderSettings
struct ExampleRef
class ExampleRefProvider
class FileAtomMapper
class FileMappedElementTyper
class FileMappedGninaTyper
class GninaIndexTyper
class GninaVectorTyper
class Grid
class Grid< Dtype, 1, isCUDA >
class GridMaker
class GroupedExampleRefProvider
class ManagedGrid
class ManagedGrid< Dtype, 1 >
class ManagedGridBase
class MappedAtomIndexTyper
struct mgrid_buffer_data
class NullIndexTyper
class Quaternion
class ReceptorStratifiedExampleRefProvider
class SamplingExampleRefProvider
class StringCache
class SubsetAtomMapper
class SubsettedElementTyper
class SubsettedGninaTyper
class Transform
class UniformExampleRefProvider
class ValueStratifiedExampleRefProfider
Typedefs
using CartesianMGrid = CartesianGrid< ManagedGrid< float, 3 > >
using cuda_float3 = ::float3
Enumerations
enum LogLevel { INFO, WARNING, ERROR, DEBUG }
Functions
cudaMemcpyKind copyKind (bool srcCUDA, bool destCUDA)
BOOST_PP_REPEAT_FROM_TO (1, LIBMOLGRID_MAX_GRID_DIM, EXPAND_GRID_DEFINITIONS, 0)
template<typename DType >
CartesianGrid< ManagedGrid< DType, 3 > > read_dx (std::istream &in)
template<typename DType >
CartesianGrid< ManagedGrid< DType, 3 > > read_dx (const std::string &fname)
template<typename Dtype >
void read_dx (std::istream &in, Grid< Dtype, 3 > &grid)
template<typename Dtype >
void read_dx (const std::string &fname, Grid< Dtype, 3 > &grid)
template<class G >
void read_bin (std::istream &in, G &grid)
template<typename DType >
void write_dx (std::ostream &out, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale=1.0)
template<typename DType >
void write_dx (const std::string &fname, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale)
template<typename Dtype >
void write_dx_grids (const std::string &prefix, const std::vector< std::string > &names, const Grid< Dtype, 4 > &grid, const float3 &center, float resolution, float scale=1.0)
template<typename Dtype >
void read_dx_grids (const std::string &prefix, const std::vector< std::string > &names, Grid< Dtype, 4 > &grid)
template<typename DType >
void write_map (std::ostream &out, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale=1.0)
template<typename DType >
void write_map (const std::string &fname, const Grid< DType, 3 > &grid, const float3 &center, float resolution, float scale)
template<class G >
void write_bin (std::ostream &out, const G &grid)
std::ostream & log (LogLevel level=INFO)
std::string ftoa (float v)
std::string itoa (int v)
BOOST_PP_REPEAT_FROM_TO (1, LIBMOLGRID_MAX_GRID_DIM, EXPAND_MGRID_DEFINITIONS, 0)
static stringstream recmap (R"(AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobe Bromine Iodine Chlorine Fluorine Nitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptor Oxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonor Sulfur SulfurAcceptor Phosphorus Calcium Zinc GenericMetal Boron Manganese Magnesium Iron)")
static stringstream ligmap (R"(AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobe Bromine Iodine Chlorine Fluorine Nitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptor Oxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonor Sulfur SulfurAcceptor Phosphorus GenericMetal Boron Manganese Magnesium Zinc Calcium Iron)")
FileMappedGninaTyper defaultGninaReceptorTyper (recmap)
FileMappedGninaTyper defaultGninaLigandTyper (ligmap)
size_t typ_vec_size (const std::vector< std::vector< float > > &t)
bool is_numeric (const string &number)
unsigned read_dx_helper (std::istream &in, float3 &center, float &res)
template void write_dx (std::ostream &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_dx (const std::string &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_dx (std::ostream &, const Grid< double, 3 > &, const float3 &, float, float)
template void write_dx (const std::string &, const Grid< double, 3 > &, const float3 &, float, float)
template void write_dx_grids (const std::string &, const std::vector< std::string > &, const Grid< float, 4 > &, const float3 &, float, float)
template void write_dx_grids (const std::string &, const std::vector< std::string > &, const Grid< double, 4 > &, const float3 &, float, float)
template void read_dx_grids (const std::string &, const std::vector< std::string > &, Grid< float, 4 > &)
template void read_dx_grids (const std::string &, const std::vector< std::string > &, Grid< double, 4 > &)
template void write_map (std::ostream &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_map (const std::string &, const Grid< float, 3 > &, const float3 &, float, float)
template void write_map (std::ostream &, const Grid< double, 3 > &, const float3 &, float, float)
template void write_map (const std::string &, const Grid< double, 3 > &, const float3 &, float, float)
Variables
FileMappedGninaTyper defaultGninaReceptorTyper
FileMappedGninaTyper defaultGninaLigandTyper
StringCache string_cache
std::default_random_engine random_engine
unsigned do_not_optimize_away
Detailed Description
quaternion.h
Typedef Documentation
CartesianMGrid
using CartesianMGrid = CartesianGrid<ManagedGrid<float, 3> >
cuda_float3
using cuda_float3 = ::float3
Enumeration Type Documentation
LogLevel
enum LogLevel
Enumerator
INFO
WARNING
ERROR
DEBUG
Function Documentation
copyKind()
cudaMemcpyKind libmolgrid::copyKind (bool srcCUDA, bool destCUDA) inline
Referenced by Grid< Dtype, NumDims, true >::copyFrom(), Grid< Dtype, 1, isCUDA >::copyFrom(), Grid< Dtype, NumDims, true >::copyTo(), and Grid< Dtype, 1, isCUDA >::copyTo().
BOOST_PP_REPEAT_FROM_TO() [1/2]
libmolgrid::BOOST_PP_REPEAT_FROM_TO (1 , LIBMOLGRID_MAX_GRID_DIM , EXPAND_GRID_DEFINITIONS , 0)
read_dx() [1/4]
template CartesianGrid< ManagedGrid< double, 3 > > read_dx (std::istream & in)
Read in dx formatted grid and return initialized grid.
read_dx() [2/4]
template CartesianGrid< ManagedGrid< double, 3 > > read_dx (const std::string & fname)
read dx grid from file name
read_dx() [3/4]
void read_dx (std::istream & in, Grid< Dtype, 3 > & grid)
Read dx formatted grid into provided grid, which must have the correct dimensions.
read_dx() [4/4]
void read_dx (const std::string & fname, Grid< Dtype, 3 > & grid)
read dx grid from file name
read_bin()
void libmolgrid::read_bin (std::istream & in, G & grid)
read in binary file, grid must be correct size
write_dx() [1/6]
void write_dx (std::ostream & out, const Grid< DType, 3 > & grid, const float3 & center, float resolution, float scale = 1.0)
output grid as dx formatted file Values are multiplied by scale, which may be necessary to adjust for limited precision in the text-based format
Referenced by write_dx(), and write_dx_grids().
write_dx() [2/6]
void write_dx (const std::string & fname, const Grid< DType, 3 > & grid, const float3 & center, float resolution, float scale = 1.0)
output dx to file name
write_dx_grids() [1/3]
void write_dx_grids (const std::string & prefix, const std::vector< std::string > & names, const Grid< Dtype, 4 > & grid, const float3 & center, float resolution, float scale = 1.0)
Output multiple grids using type names as a suffix.
Parameters
[in] prefix filename will have form [prefix]_[typename].dx
[in] names must have same size as first dimension of grid
[in] grid input grids
[in] center
[in] resolution
[in] scale multiply each value by this factor
read_dx_grids() [1/3]
void read_dx_grids (const std::string & prefix, const std::vector< std::string > & names, Grid< Dtype, 4 > & grid)
Read multiple grids using type names as a suffix. Grids must be correctly sized.
Parameters
[in] prefix filename will have form [prefix]_[typename].dx
[in] names must have same size as first dimension of grid
[in] grid input grids
[in] center
[in] resolution
[in] scale multiply each value by this factor
write_map() [1/6]
void write_map (std::ostream & out, const Grid< DType, 3 > & grid, const float3 & center, float resolution, float scale = 1.0)
output grid as autodock map formatted file
output autodock4 to stream
Referenced by write_map().
write_map() [2/6]
void write_map (const std::string & fname, const Grid< DType, 3 > & grid, const float3 & center, float resolution, float scale = 1.0)
output autodock4 to filename
write_bin()
void libmolgrid::write_bin (std::ostream & out, const G & grid)
log()
std::ostream& libmolgrid::log (LogLevel level = INFO) inline
Referenced by GroupedExampleRefProvider< Provider >::addref(), ReceptorStratifiedExampleRefProvider< Provider, K >::setup(), and ValueStratifiedExampleRefProfider< Provider >::setup().
ftoa()
std::string libmolgrid::ftoa (float v) inline
itoa()
std::string libmolgrid::itoa (int v) inline
Referenced by BalancedExampleRefProvider::addref(), ManagedGridBase< Dtype, 1 >::alloc_and_set_cpu(), ManagedGridBase< Dtype, 1 >::alloc_and_set_gpu(), GridMaker::backward(), GroupedExampleRefProvider< Provider >::check_batch_size(), Grid< Dtype, NumDims, true >::check_index(), Grid< Dtype, 1, isCUDA >::check_index(), GridMaker::check_index_args(), GridMaker::check_vector_args(), CoordinateSet::CoordinateSet(), CoordinateSet::copyTo(), Example::extract_label(), Example::extract_labels(), GridMaker::forward(), ExampleExtractor::get_type_names(), CoordinateSet::make_vector_types(), Example::merge_coordinates(), read_dx(), read_dx_grids(), read_dx_helper(), Example::sum_types(), CoordinateSet::sum_types(), and write_dx_grids().
BOOST_PP_REPEAT_FROM_TO() [2/2]
libmolgrid::BOOST_PP_REPEAT_FROM_TO (1 , LIBMOLGRID_MAX_GRID_DIM , EXPAND_MGRID_DEFINITIONS , 0)
recmap()
static stringstream libmolgrid::recmap (R"(AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobeBromine Iodine Chlorine FluorineNitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptorOxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonorSulfur SulfurAcceptorPhosphorus CalciumZincGenericMetal Boron Manganese Magnesium Iron)") static
ligmap()
static stringstream libmolgrid::ligmap (R"(AliphaticCarbonXSHydrophobe AliphaticCarbonXSNonHydrophobe AromaticCarbonXSHydrophobe AromaticCarbonXSNonHydrophobeBromine IodineChlorineFluorineNitrogen NitrogenXSAcceptor NitrogenXSDonor NitrogenXSDonorAcceptorOxygen OxygenXSAcceptor OxygenXSDonorAcceptor OxygenXSDonorSulfur SulfurAcceptorPhosphorusGenericMetal Boron Manganese Magnesium Zinc Calcium Iron)") static
defaultGninaReceptorTyper()
FileMappedGninaTyper libmolgrid::defaultGninaReceptorTyper (recmap)
defaultGninaLigandTyper()
FileMappedGninaTyper libmolgrid::defaultGninaLigandTyper (ligmap)
typ_vec_size()
size_t libmolgrid::typ_vec_size (const std::vector< std::vector< float > > & t) inline
is_numeric()
bool libmolgrid::is_numeric (const string & number)
Referenced by ExampleRef::ExampleRef().
read_dx_helper()
unsigned libmolgrid::read_dx_helper (std::istream & in, float3 & center, float & res)
Referenced by read_dx().
write_dx() [3/6]
template void libmolgrid::write_dx (std::ostream & , const Grid< float, 3 > & , const float3 & , float , float)
write_dx() [4/6]
template void libmolgrid::write_dx (const std::string & , const Grid< float, 3 > & , const float3 & , float , float)
write_dx() [5/6]
template void libmolgrid::write_dx (std::ostream & , const Grid< double, 3 > & , const float3 & , float , float)
write_dx() [6/6]
template void libmolgrid::write_dx (const std::string & , const Grid< double, 3 > & , const float3 & , float , float)
write_dx_grids() [2/3]
template void libmolgrid::write_dx_grids (const std::string & , const std::vector< std::string > & , const Grid< float, 4 > & , const float3 & , float , float)
write_dx_grids() [3/3]
template void libmolgrid::write_dx_grids (const std::string & , const std::vector< std::string > & , const Grid< double, 4 > & , const float3 & , float , float)
read_dx_grids() [2/3]
template void libmolgrid::read_dx_grids (const std::string & , const std::vector< std::string > & , Grid< float, 4 > &)
read_dx_grids() [3/3]
template void libmolgrid::read_dx_grids (const std::string & , const std::vector< std::string > & , Grid< double, 4 > &)
write_map() [3/6]
template void libmolgrid::write_map (std::ostream & , const Grid< float, 3 > & , const float3 & , float , float)
write_map() [4/6]
template void libmolgrid::write_map (const std::string & , const Grid< float, 3 > & , const float3 & , float , float)
write_map() [5/6]
template void libmolgrid::write_map (std::ostream & , const Grid< double, 3 > & , const float3 & , float , float)
write_map() [6/6]
template void libmolgrid::write_map (const std::string & , const Grid< double, 3 > & , const float3 & , float , float)
Variable Documentation
defaultGninaReceptorTyper
FileMappedGninaTyper defaultGninaReceptorTyper(recmap)
defaultGninaLigandTyper
FileMappedGninaTyper defaultGninaLigandTyper(ligmap)
string_cache
StringCache string_cache
Referenced by CoordCache::CoordCache(), ExampleRef::ExampleRef(), and GroupedExampleRefProvider< Provider >::nextref().
random_engine
std::default_random_engine random_engine
random engine used in libmolgrid
Referenced by SamplingExampleRefProvider< Provider1, Provider2 >::nextref(), ReceptorStratifiedExampleRefProvider< Provider, K >::nextref(), ReceptorStratifiedExampleRefProvider< Provider, K >::setup(), UniformExampleRefProvider::setup(), and Transform::Transform().
do_not_optimize_away
unsigned do_not_optimize_away
Referenced by CoordCache::CoordCache().